
<?php $this->extends('layout.phtml') ?>
<html>
<body id="completed">
<?php $this->begin('content') ?>
<nav class="site-nav">
  <a href="<?=header('Location: index.php')?>">Home</a>

<!-- dit nog aanpassen dat ie naar de begin pagina gaat-->
</nav>
<section class="completed">
	<h2>You are finished</h2>
	<dl>
	<?php foreach ($domain->goals as $goal): ?>
		<?php if ($goal->hasAnswers() && (($answer = $goal->answer($state)) || $state->facts[$goal->name] != STATE_UNDEFINED)): ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?></dt>
			<dd><?php
				echo $answer
					? $state->substitute_variables($answer->description, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				?></dd>
			<?php endif ?>
	<?php endforeach ?>
	</dl>
</section>
<?php $this->end() ?>

</body>
</html>
