<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="question">
	<p><?=$state->substitute_variables($question->description, ['Template', 'html'])?></p>
		<ul class="options">
			<?php foreach ($question->options as $option): ?>
				<li>
					<label>
						<input type="checkbox" value="<?=_encode($option->consequences)?>">
						<?=$state->substitute_variables($option->description, ['Template', 'html'])?>
					</label>
				</li>
			<?php endforeach ?>
			<?php if($skippable): ?>
			<li class="skip-option">
				<label>
					<input type="radio" name="answer" value="<?=_encode(array())?>">
					I don't know
				</label>
			</li>
			<?php endif ?>
		</ul>
			<ol class="submit-option">
				<label>
					<input type="submit" value="Submit">
				</label>
			</ol>
</section>
<?php $this->end() ?>
