<?php $this->extends('layout2.phtml') ?>

<?php $this->begin('content') ?>
<section class="question">
	<p><?=$state->substitute_variables($question->description, ['Template', 'html'])?></p>
		<ol class="options">
			<?php foreach ($question->options as $option): ?>
			  <li>
					<label>
						<input type="checkbox" name="answer" value="<?=_encode($option->consequences)?>">
						<?=$state->substitute_variables($option->description, ['Template', 'html'])?>
					</label>
				</li>
			<?php endforeach ?>
			<input type="submit" value="Submit">
	</ol>

</section>
<?php $this->end() ?>
