<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="question">
	<p><?=$state->substitute_variables($question->description, ['Template', 'html'])?></p>
	<label>
		<input type="number" id="quantity" name="quantity" value="<?php echo $question->consequences;?>">
	</label>
	<ol class="submit-option">
		<label>
			<input type="submit" value="Submit">
		</label>
	</ol>
</section>
<?php $this->end() ?>
