<!DOCTYPE html>
<html>
	<head>
		<title>Inference engine</title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body id="kennisbanken">
		<nav class="site-nav">
			<b ?>Diabetes Knowledge System</b><!-- what should come here? naam???? -->
		</nav>
		<header>
			<h1>Inference engine</h1>
		</header>


		<section class="upload-knowledge-base-form">
			<h2>Diabetes Risk Assessment and Lifestyle Advice System</h2>
			<form method="post" enctype="application/x-www-form-urlencoded">
				<div>
					<label for="input-knowledgebase">This test will assess your diabetes type 1 and/or type 2 risk and will offer lifestyle improvement tips on the basis of your answers to a set of questions. For an optimal treatment and/or prevention of diabetes, it is is extremely important to be aware of your diabetes condition or risk in time. Also, your life with diabetes and your risk of getting diabetes can be significantly improved by adjusting your lifestyle.

					This test will take approximately 10 minutes.

					(Disclaimer: This risk assessment is based on the expertise provided by a national diabetes expert. This system hereby follows the general diabetes risk guidelines, as provided by the NHG assocation for general practioners in the Netherlands. It is a general risk assesment and not a 100% accurate diabetes test. If you have any doubts or worries about this risk assessment, we advice you to visit your general practioner and take an actual diabetes test) </label>
				 	<!-- <input type="file" name="knowledgebase" id="input-knowledgebase"> -->
				</div>

				<div class="controls">
					<button type="submit" name="action" value="run">Start</button>
					<!-- <button type="submit" name="action" value="analyse">Analyse</button>-->
				</div>
			</form>
		</section>

		<footer>
			<p>Source code available on: <a href="https://github.com/anniektheuwissen/Diabetes-Knowledge-System">Github</a>.</p>
		</footer>
	</body>
</html>
