<!DOCTYPE html>
<html>
	<head>
		<title>Inference engine</title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body id="kennisbanken">
		<nav class="site-nav">
			<!-- what should come here? naam???? -->
		</nav>
		<header>
			<h1>Inference engine</h1>
		</header>


		<section class="upload-knowledge-base-form">
			<h2>Diabetes Risk Assessment and Lifestyle Advice System</h2>
			<form method="post" enctype="application/x-www-form-urlencoded">
				<div>
					<label for="input-knowledgebase">This system will AANVULLEN</label>
				 	<!-- <input type="file" name="knowledgebase" id="input-knowledgebase"> -->
				</div>

				<div class="controls">
					<button type="submit" name="action" value="run">Start</button>
					<!-- <button type="submit" name="action" value="analyse">Analyse</button>-->
				</div>
			</form>
		</section>

		<div class="image">
			<img src='<?php echo $this->getViewFileUrl('../../diabetesfonds.png'); ?>' alt="image-icon" width="30" height="25">
		</div>

		<footer>
			<p>Source code available on: <a href="https://github.com/anniektheuwissen/Diabetes-Knowledge-System">Github</a>.</p>
		</footer>
	</body>
</html>
